import express from 'express';
import cors from 'cors';
import path from 'path';
import { createServer as createViteServer } from 'vite';
import { GoogleGenAI } from '@google/genai';

const app = express();
const PORT = 3000;

app.use(cors());
app.use(express.json({ limit: '10mb' }));

// Health check endpoint
app.get('/api/health', (_req, res) => {
  res.json({ status: 'ok' });
});

// Poster AI art generator endpoint
app.post('/api/generate-poster', async (req, res) => {
  try {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return res.status(400).json({
        error: 'GEMINI_API_KEY environment variable is missing. Configure GEMINI_API_KEY in your environment secrets.'
      });
    }

    const { prompt, title, theme, type, location, description, rules, rentalInfo, bgImageUrl } = req.body;

    const ai = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build'
        }
      }
    });

    const fullPrompt = prompt || `High-end razor-sharp 3D airsoft promotional event poster background art for "Bosjol Tactical Airsoft Field". 
Event Title: ${title || 'Tactical Skirmish Mission'}.
Game Type: ${type || 'Airsoft Match'}.
Operational Theme/Mode: ${theme || 'CQB Operations'}.
Arena Field Location: ${location || 'Pretoria Field'}.
Mission Details: ${description || 'Fast-paced tactical airsoft engagement with team objectives.'}.
Equipment/Rentals: ${rentalInfo || 'AEG Rifles, Face Protection, Bio BBs'}.
Style: Cinematic, high contrast, gritty 3D tactical airsoft action, razor sharp detail, intense dramatic atmospheric smoke lighting, professional promotional esports & mil-sim poster art. Aspect ratio portrait 3:4. Clean cinematic background artwork without text overlay.`;

    const parts: any[] = [];
    
    // If user provided an existing uploaded image or background image, pass it to Gemini as inline data for image-to-image/reference!
    if (bgImageUrl && typeof bgImageUrl === 'string' && bgImageUrl.startsWith('data:image/')) {
      const matches = bgImageUrl.match(/^data:(image\/\w+);base64,(.+)$/);
      if (matches) {
        parts.push({
          inlineData: {
            mimeType: matches[1],
            data: matches[2]
          }
        });
      }
    }

    parts.push({ text: fullPrompt });

    const response = await ai.models.generateContent({
      model: 'gemini-3.1-flash-lite-image',
      contents: {
        parts
      },
      config: {
        imageConfig: {
          aspectRatio: '3:4'
        }
      }
    });

    let imageUrl = '';
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          imageUrl = `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!imageUrl) {
      return res.status(500).json({ error: 'No image generated by the AI model.' });
    }

    res.json({ imageUrl, success: true });
  } catch (error: any) {
    console.error('Error generating poster art:', error);
    res.status(500).json({ error: error.message || 'Failed to generate poster art.' });
  }
});

async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa'
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (_req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
