import express from 'express';
import cors from 'cors';
import path from 'path';
import { createServer as createViteServer } from 'vite';
import { GoogleGenAI } from '@google/genai';

const app = express();
const PORT = 3000;

app.use(cors());
app.use(express.json({ limit: '10mb' }));

// Health check endpoint
app.get('/api/health', (_req, res) => {
  res.json({ status: 'ok' });
});

// Poster AI art generator endpoint
app.post('/api/generate-poster', async (req, res) => {
  try {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return res.status(400).json({
        error: 'GEMINI_API_KEY environment variable is missing. Configure GEMINI_API_KEY in your environment secrets.'
      });
    }

    const { prompt, title, theme, location } = req.body;

    const ai = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build'
        }
      }
    });

    const fullPrompt = prompt || `High-end razor-sharp epic tactical airsoft promotional event poster background art for "Bosjol Tactical Airsoft Field". 
Event Title: ${title || 'Tactical Skirmish Mission'}.
Theme: ${theme || 'CQB Operations'}. Location: ${location || 'Pretoria Field'}.
Style: Cinematic, high contrast, gritty tactical action, razor sharp detail, intense dramatic atmospheric lighting, professional promotional esports & mil-sim poster art. Aspect ratio portrait 3:4. Clean cinematic background art with no messy AI text overlays.`;

    const response = await ai.models.generateContent({
      model: 'gemini-3.1-flash-lite-image',
      contents: {
        parts: [{ text: fullPrompt }]
      },
      config: {
        imageConfig: {
          aspectRatio: '3:4'
        }
      }
    });

    let imageUrl = '';
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          imageUrl = `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!imageUrl) {
      return res.status(500).json({ error: 'No image generated by the AI model.' });
    }

    res.json({ imageUrl, success: true });
  } catch (error: any) {
    console.error('Error generating poster art:', error);
    res.status(500).json({ error: error.message || 'Failed to generate poster art.' });
  }
});

async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa'
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (_req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
